import { Cambay } from "next/font/google";
import "./globals.css";
import HomePage from "./Home/Page";
import Footer from "@/components/Footer";

const cambay = Cambay({
  subsets: ['latin'],
  weight: ['400','700'], 
  variable: '--font-cambay', 
  display: 'swap',
})

export const metadata = {
  title: "Care Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cambay.variable}`}
      >
        <HomePage/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
